// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: recording_shelves.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordingShelfBridge_UpsertRoomRecording_FullMethodName = "/shelves.recording.RecordingShelfBridge/UpsertRoomRecording"
)

// RecordingShelfBridgeClient is the client API for RecordingShelfBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordingShelfBridgeClient interface {
	UpsertRoomRecording(ctx context.Context, in *UpsertRoomRecordingRequest, opts ...grpc.CallOption) (*UpsertRoomRecordingResponse, error)
}

type recordingShelfBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingShelfBridgeClient(cc grpc.ClientConnInterface) RecordingShelfBridgeClient {
	return &recordingShelfBridgeClient{cc}
}

func (c *recordingShelfBridgeClient) UpsertRoomRecording(ctx context.Context, in *UpsertRoomRecordingRequest, opts ...grpc.CallOption) (*UpsertRoomRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRoomRecordingResponse)
	err := c.cc.Invoke(ctx, RecordingShelfBridge_UpsertRoomRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordingShelfBridgeServer is the server API for RecordingShelfBridge service.
// All implementations must embed UnimplementedRecordingShelfBridgeServer
// for forward compatibility.
type RecordingShelfBridgeServer interface {
	UpsertRoomRecording(context.Context, *UpsertRoomRecordingRequest) (*UpsertRoomRecordingResponse, error)
	mustEmbedUnimplementedRecordingShelfBridgeServer()
}

// UnimplementedRecordingShelfBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordingShelfBridgeServer struct{}

func (UnimplementedRecordingShelfBridgeServer) UpsertRoomRecording(context.Context, *UpsertRoomRecordingRequest) (*UpsertRoomRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRoomRecording not implemented")
}
func (UnimplementedRecordingShelfBridgeServer) mustEmbedUnimplementedRecordingShelfBridgeServer() {}
func (UnimplementedRecordingShelfBridgeServer) testEmbeddedByValue()                              {}

// UnsafeRecordingShelfBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingShelfBridgeServer will
// result in compilation errors.
type UnsafeRecordingShelfBridgeServer interface {
	mustEmbedUnimplementedRecordingShelfBridgeServer()
}

func RegisterRecordingShelfBridgeServer(s grpc.ServiceRegistrar, srv RecordingShelfBridgeServer) {
	// If the following call panics, it indicates UnimplementedRecordingShelfBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordingShelfBridge_ServiceDesc, srv)
}

func _RecordingShelfBridge_UpsertRoomRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRoomRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingShelfBridgeServer).UpsertRoomRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingShelfBridge_UpsertRoomRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingShelfBridgeServer).UpsertRoomRecording(ctx, req.(*UpsertRoomRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordingShelfBridge_ServiceDesc is the grpc.ServiceDesc for RecordingShelfBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingShelfBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shelves.recording.RecordingShelfBridge",
	HandlerType: (*RecordingShelfBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertRoomRecording",
			Handler:    _RecordingShelfBridge_UpsertRoomRecording_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recording_shelves.proto",
}
