// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: recording_shelves.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordingStatus int32

const (
	RecordingStatus_RECORDING_STATUS_UNSPECIFIED RecordingStatus = 0
	RecordingStatus_RECORDING_STATUS_RECORDING   RecordingStatus = 1
	RecordingStatus_RECORDING_STATUS_COMPLETED   RecordingStatus = 2
	RecordingStatus_RECORDING_STATUS_FAILED      RecordingStatus = 3
)

// Enum value maps for RecordingStatus.
var (
	RecordingStatus_name = map[int32]string{
		0: "RECORDING_STATUS_UNSPECIFIED",
		1: "RECORDING_STATUS_RECORDING",
		2: "RECORDING_STATUS_COMPLETED",
		3: "RECORDING_STATUS_FAILED",
	}
	RecordingStatus_value = map[string]int32{
		"RECORDING_STATUS_UNSPECIFIED": 0,
		"RECORDING_STATUS_RECORDING":   1,
		"RECORDING_STATUS_COMPLETED":   2,
		"RECORDING_STATUS_FAILED":      3,
	}
)

func (x RecordingStatus) Enum() *RecordingStatus {
	p := new(RecordingStatus)
	*p = x
	return p
}

func (x RecordingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_shelves_proto_enumTypes[0].Descriptor()
}

func (RecordingStatus) Type() protoreflect.EnumType {
	return &file_recording_shelves_proto_enumTypes[0]
}

func (x RecordingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordingStatus.Descriptor instead.
func (RecordingStatus) EnumDescriptor() ([]byte, []int) {
	return file_recording_shelves_proto_rawDescGZIP(), []int{0}
}

type UpsertRoomRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	Status        RecordingStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=shelves.recording.RecordingStatus" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	S3Prefix      string                 `protobuf:"bytes,6,opt,name=s3_prefix,json=s3Prefix,proto3" json:"s3_prefix,omitempty"`
	MetadataKey   string                 `protobuf:"bytes,7,opt,name=metadata_key,json=metadataKey,proto3" json:"metadata_key,omitempty"`
	TimelineKey   string                 `protobuf:"bytes,8,opt,name=timeline_key,json=timelineKey,proto3" json:"timeline_key,omitempty"`
	ServiceId     string                 `protobuf:"bytes,9,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRoomRecordingRequest) Reset() {
	*x = UpsertRoomRecordingRequest{}
	mi := &file_recording_shelves_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoomRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoomRecordingRequest) ProtoMessage() {}

func (x *UpsertRoomRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_shelves_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRoomRecordingRequest.ProtoReflect.Descriptor instead.
func (*UpsertRoomRecordingRequest) Descriptor() ([]byte, []int) {
	return file_recording_shelves_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertRoomRecordingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpsertRoomRecordingRequest) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *UpsertRoomRecordingRequest) GetStatus() RecordingStatus {
	if x != nil {
		return x.Status
	}
	return RecordingStatus_RECORDING_STATUS_UNSPECIFIED
}

func (x *UpsertRoomRecordingRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *UpsertRoomRecordingRequest) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *UpsertRoomRecordingRequest) GetS3Prefix() string {
	if x != nil {
		return x.S3Prefix
	}
	return ""
}

func (x *UpsertRoomRecordingRequest) GetMetadataKey() string {
	if x != nil {
		return x.MetadataKey
	}
	return ""
}

func (x *UpsertRoomRecordingRequest) GetTimelineKey() string {
	if x != nil {
		return x.TimelineKey
	}
	return ""
}

func (x *UpsertRoomRecordingRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type UpsertRoomRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,4,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRoomRecordingResponse) Reset() {
	*x = UpsertRoomRecordingResponse{}
	mi := &file_recording_shelves_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoomRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoomRecordingResponse) ProtoMessage() {}

func (x *UpsertRoomRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_shelves_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRoomRecordingResponse.ProtoReflect.Descriptor instead.
func (*UpsertRoomRecordingResponse) Descriptor() ([]byte, []int) {
	return file_recording_shelves_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertRoomRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpsertRoomRecordingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertRoomRecordingResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpsertRoomRecordingResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

var File_recording_shelves_proto protoreflect.FileDescriptor

const file_recording_shelves_proto_rawDesc = "" +
	"\n" +
	"\x17recording_shelves.proto\x12\x11shelves.recording\"\xd8\x02\n" +
	"\x1aUpsertRoomRecordingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".shelves.recording.RecordingStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAt\x12\x1b\n" +
	"\ts3_prefix\x18\x06 \x01(\tR\bs3Prefix\x12!\n" +
	"\fmetadata_key\x18\a \x01(\tR\vmetadataKey\x12!\n" +
	"\ftimeline_key\x18\b \x01(\tR\vtimelineKey\x12\x1d\n" +
	"\n" +
	"service_id\x18\t \x01(\tR\tserviceId\"\x8d\x01\n" +
	"\x1bUpsertRoomRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x04 \x01(\tR\vrecordingId*\x90\x01\n" +
	"\x0fRecordingStatus\x12 \n" +
	"\x1cRECORDING_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRECORDING_STATUS_RECORDING\x10\x01\x12\x1e\n" +
	"\x1aRECORDING_STATUS_COMPLETED\x10\x02\x12\x1b\n" +
	"\x17RECORDING_STATUS_FAILED\x10\x032\x8c\x01\n" +
	"\x14RecordingShelfBridge\x12t\n" +
	"\x13UpsertRoomRecording\x12-.shelves.recording.UpsertRoomRecordingRequest\x1a..shelves.recording.UpsertRoomRecordingResponseB&Z$github.com/brollyhub/recording/protob\x06proto3"

var (
	file_recording_shelves_proto_rawDescOnce sync.Once
	file_recording_shelves_proto_rawDescData []byte
)

func file_recording_shelves_proto_rawDescGZIP() []byte {
	file_recording_shelves_proto_rawDescOnce.Do(func() {
		file_recording_shelves_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recording_shelves_proto_rawDesc), len(file_recording_shelves_proto_rawDesc)))
	})
	return file_recording_shelves_proto_rawDescData
}

var file_recording_shelves_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recording_shelves_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recording_shelves_proto_goTypes = []any{
	(RecordingStatus)(0),                // 0: shelves.recording.RecordingStatus
	(*UpsertRoomRecordingRequest)(nil),  // 1: shelves.recording.UpsertRoomRecordingRequest
	(*UpsertRoomRecordingResponse)(nil), // 2: shelves.recording.UpsertRoomRecordingResponse
}
var file_recording_shelves_proto_depIdxs = []int32{
	0, // 0: shelves.recording.UpsertRoomRecordingRequest.status:type_name -> shelves.recording.RecordingStatus
	1, // 1: shelves.recording.RecordingShelfBridge.UpsertRoomRecording:input_type -> shelves.recording.UpsertRoomRecordingRequest
	2, // 2: shelves.recording.RecordingShelfBridge.UpsertRoomRecording:output_type -> shelves.recording.UpsertRoomRecordingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recording_shelves_proto_init() }
func file_recording_shelves_proto_init() {
	if File_recording_shelves_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recording_shelves_proto_rawDesc), len(file_recording_shelves_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recording_shelves_proto_goTypes,
		DependencyIndexes: file_recording_shelves_proto_depIdxs,
		EnumInfos:         file_recording_shelves_proto_enumTypes,
		MessageInfos:      file_recording_shelves_proto_msgTypes,
	}.Build()
	File_recording_shelves_proto = out.File
	file_recording_shelves_proto_goTypes = nil
	file_recording_shelves_proto_depIdxs = nil
}
