// recording_sfu.proto
// Protocol definitions for SFU ↔ Recording Service communication
// This defines the bidirectional gRPC stream for recording RTP packets
// and room events for server-side recording.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: recording_sfu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoCanRecord int32

const (
	WhoCanRecord_WHO_CAN_RECORD_UNSPECIFIED WhoCanRecord = 0
	WhoCanRecord_HOST_ONLY                  WhoCanRecord = 1
	WhoCanRecord_CO_HOST_AND_HOST           WhoCanRecord = 2
	WhoCanRecord_ANYONE                     WhoCanRecord = 3
)

// Enum value maps for WhoCanRecord.
var (
	WhoCanRecord_name = map[int32]string{
		0: "WHO_CAN_RECORD_UNSPECIFIED",
		1: "HOST_ONLY",
		2: "CO_HOST_AND_HOST",
		3: "ANYONE",
	}
	WhoCanRecord_value = map[string]int32{
		"WHO_CAN_RECORD_UNSPECIFIED": 0,
		"HOST_ONLY":                  1,
		"CO_HOST_AND_HOST":           2,
		"ANYONE":                     3,
	}
)

func (x WhoCanRecord) Enum() *WhoCanRecord {
	p := new(WhoCanRecord)
	*p = x
	return p
}

func (x WhoCanRecord) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WhoCanRecord) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_sfu_proto_enumTypes[0].Descriptor()
}

func (WhoCanRecord) Type() protoreflect.EnumType {
	return &file_recording_sfu_proto_enumTypes[0]
}

func (x WhoCanRecord) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WhoCanRecord.Descriptor instead.
func (WhoCanRecord) EnumDescriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{0}
}

type AccessLevel int32

const (
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	AccessLevel_ACCESS_ALL               AccessLevel = 1
	AccessLevel_ACCESS_HOST              AccessLevel = 2
	AccessLevel_ACCESS_LOGGED_IN         AccessLevel = 3
	AccessLevel_ACCESS_SELECTED          AccessLevel = 4
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "ACCESS_ALL",
		2: "ACCESS_HOST",
		3: "ACCESS_LOGGED_IN",
		4: "ACCESS_SELECTED",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"ACCESS_ALL":               1,
		"ACCESS_HOST":              2,
		"ACCESS_LOGGED_IN":         3,
		"ACCESS_SELECTED":          4,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_sfu_proto_enumTypes[1].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_recording_sfu_proto_enumTypes[1]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{1}
}

type TrackType int32

const (
	TrackType_TRACK_TYPE_UNSPECIFIED TrackType = 0
	TrackType_AUDIO                  TrackType = 1
	TrackType_VIDEO                  TrackType = 2
	TrackType_SCREENSHARE            TrackType = 3
)

// Enum value maps for TrackType.
var (
	TrackType_name = map[int32]string{
		0: "TRACK_TYPE_UNSPECIFIED",
		1: "AUDIO",
		2: "VIDEO",
		3: "SCREENSHARE",
	}
	TrackType_value = map[string]int32{
		"TRACK_TYPE_UNSPECIFIED": 0,
		"AUDIO":                  1,
		"VIDEO":                  2,
		"SCREENSHARE":            3,
	}
)

func (x TrackType) Enum() *TrackType {
	p := new(TrackType)
	*p = x
	return p
}

func (x TrackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackType) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_sfu_proto_enumTypes[2].Descriptor()
}

func (TrackType) Type() protoreflect.EnumType {
	return &file_recording_sfu_proto_enumTypes[2]
}

func (x TrackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackType.Descriptor instead.
func (TrackType) EnumDescriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{2}
}

type RecordingLayout int32

const (
	RecordingLayout_RECORDING_LAYOUT_UNSPECIFIED RecordingLayout = 0
	RecordingLayout_RECORDING_LAYOUT_GRID        RecordingLayout = 1
)

// Enum value maps for RecordingLayout.
var (
	RecordingLayout_name = map[int32]string{
		0: "RECORDING_LAYOUT_UNSPECIFIED",
		1: "RECORDING_LAYOUT_GRID",
	}
	RecordingLayout_value = map[string]int32{
		"RECORDING_LAYOUT_UNSPECIFIED": 0,
		"RECORDING_LAYOUT_GRID":        1,
	}
)

func (x RecordingLayout) Enum() *RecordingLayout {
	p := new(RecordingLayout)
	*p = x
	return p
}

func (x RecordingLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordingLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_recording_sfu_proto_enumTypes[3].Descriptor()
}

func (RecordingLayout) Type() protoreflect.EnumType {
	return &file_recording_sfu_proto_enumTypes[3]
}

func (x RecordingLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordingLayout.Descriptor instead.
func (RecordingLayout) EnumDescriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{3}
}

type RecordingToSfu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*RecordingToSfu_RegisterResponse
	//	*RecordingToSfu_StartRecordingResponse
	//	*RecordingToSfu_StopRecordingResponse
	//	*RecordingToSfu_Error
	//	*RecordingToSfu_Heartbeat
	Message       isRecordingToSfu_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingToSfu) Reset() {
	*x = RecordingToSfu{}
	mi := &file_recording_sfu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingToSfu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingToSfu) ProtoMessage() {}

func (x *RecordingToSfu) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingToSfu.ProtoReflect.Descriptor instead.
func (*RecordingToSfu) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{0}
}

func (x *RecordingToSfu) GetMessage() isRecordingToSfu_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RecordingToSfu) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Message.(*RecordingToSfu_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *RecordingToSfu) GetStartRecordingResponse() *StartRecordingResponse {
	if x != nil {
		if x, ok := x.Message.(*RecordingToSfu_StartRecordingResponse); ok {
			return x.StartRecordingResponse
		}
	}
	return nil
}

func (x *RecordingToSfu) GetStopRecordingResponse() *StopRecordingResponse {
	if x != nil {
		if x, ok := x.Message.(*RecordingToSfu_StopRecordingResponse); ok {
			return x.StopRecordingResponse
		}
	}
	return nil
}

func (x *RecordingToSfu) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Message.(*RecordingToSfu_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RecordingToSfu) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*RecordingToSfu_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isRecordingToSfu_Message interface {
	isRecordingToSfu_Message()
}

type RecordingToSfu_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type RecordingToSfu_StartRecordingResponse struct {
	StartRecordingResponse *StartRecordingResponse `protobuf:"bytes,2,opt,name=start_recording_response,json=startRecordingResponse,proto3,oneof"`
}

type RecordingToSfu_StopRecordingResponse struct {
	StopRecordingResponse *StopRecordingResponse `protobuf:"bytes,3,opt,name=stop_recording_response,json=stopRecordingResponse,proto3,oneof"`
}

type RecordingToSfu_Error struct {
	Error *ErrorMessage `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type RecordingToSfu_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*RecordingToSfu_RegisterResponse) isRecordingToSfu_Message() {}

func (*RecordingToSfu_StartRecordingResponse) isRecordingToSfu_Message() {}

func (*RecordingToSfu_StopRecordingResponse) isRecordingToSfu_Message() {}

func (*RecordingToSfu_Error) isRecordingToSfu_Message() {}

func (*RecordingToSfu_Heartbeat) isRecordingToSfu_Message() {}

type SfuToRecording struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SfuToRecording_Register
	//	*SfuToRecording_StartRecording
	//	*SfuToRecording_StopRecording
	//	*SfuToRecording_SubscribeTrack
	//	*SfuToRecording_UnsubscribeTrack
	//	*SfuToRecording_RtpPacket
	//	*SfuToRecording_RoomEvent
	//	*SfuToRecording_Heartbeat
	Message       isSfuToRecording_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SfuToRecording) Reset() {
	*x = SfuToRecording{}
	mi := &file_recording_sfu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SfuToRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SfuToRecording) ProtoMessage() {}

func (x *SfuToRecording) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SfuToRecording.ProtoReflect.Descriptor instead.
func (*SfuToRecording) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *SfuToRecording) GetMessage() isSfuToRecording_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SfuToRecording) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *SfuToRecording) GetStartRecording() *StartRecordingRequest {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_StartRecording); ok {
			return x.StartRecording
		}
	}
	return nil
}

func (x *SfuToRecording) GetStopRecording() *StopRecordingRequest {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_StopRecording); ok {
			return x.StopRecording
		}
	}
	return nil
}

func (x *SfuToRecording) GetSubscribeTrack() *SubscribeTrackRequest {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_SubscribeTrack); ok {
			return x.SubscribeTrack
		}
	}
	return nil
}

func (x *SfuToRecording) GetUnsubscribeTrack() *UnsubscribeTrackRequest {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_UnsubscribeTrack); ok {
			return x.UnsubscribeTrack
		}
	}
	return nil
}

func (x *SfuToRecording) GetRtpPacket() *RtpPacket {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_RtpPacket); ok {
			return x.RtpPacket
		}
	}
	return nil
}

func (x *SfuToRecording) GetRoomEvent() *RoomEvent {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_RoomEvent); ok {
			return x.RoomEvent
		}
	}
	return nil
}

func (x *SfuToRecording) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*SfuToRecording_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSfuToRecording_Message interface {
	isSfuToRecording_Message()
}

type SfuToRecording_Register struct {
	// Registration
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type SfuToRecording_StartRecording struct {
	// Recording control
	StartRecording *StartRecordingRequest `protobuf:"bytes,2,opt,name=start_recording,json=startRecording,proto3,oneof"`
}

type SfuToRecording_StopRecording struct {
	StopRecording *StopRecordingRequest `protobuf:"bytes,3,opt,name=stop_recording,json=stopRecording,proto3,oneof"`
}

type SfuToRecording_SubscribeTrack struct {
	// Track management
	SubscribeTrack *SubscribeTrackRequest `protobuf:"bytes,4,opt,name=subscribe_track,json=subscribeTrack,proto3,oneof"`
}

type SfuToRecording_UnsubscribeTrack struct {
	UnsubscribeTrack *UnsubscribeTrackRequest `protobuf:"bytes,5,opt,name=unsubscribe_track,json=unsubscribeTrack,proto3,oneof"`
}

type SfuToRecording_RtpPacket struct {
	// Media data
	RtpPacket *RtpPacket `protobuf:"bytes,6,opt,name=rtp_packet,json=rtpPacket,proto3,oneof"`
}

type SfuToRecording_RoomEvent struct {
	// Room events for timeline
	RoomEvent *RoomEvent `protobuf:"bytes,7,opt,name=room_event,json=roomEvent,proto3,oneof"`
}

type SfuToRecording_Heartbeat struct {
	// Keep-alive
	Heartbeat *Heartbeat `protobuf:"bytes,8,opt,name=heartbeat,proto3,oneof"`
}

func (*SfuToRecording_Register) isSfuToRecording_Message() {}

func (*SfuToRecording_StartRecording) isSfuToRecording_Message() {}

func (*SfuToRecording_StopRecording) isSfuToRecording_Message() {}

func (*SfuToRecording_SubscribeTrack) isSfuToRecording_Message() {}

func (*SfuToRecording_UnsubscribeTrack) isSfuToRecording_Message() {}

func (*SfuToRecording_RtpPacket) isSfuToRecording_Message() {}

func (*SfuToRecording_RoomEvent) isSfuToRecording_Message() {}

func (*SfuToRecording_Heartbeat) isSfuToRecording_Message() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SfuId         string                 `protobuf:"bytes,1,opt,name=sfu_id,json=sfuId,proto3" json:"sfu_id,omitempty"`
	SfuHost       string                 `protobuf:"bytes,2,opt,name=sfu_host,json=sfuHost,proto3" json:"sfu_host,omitempty"`
	SfuPort       int32                  `protobuf:"varint,3,opt,name=sfu_port,json=sfuPort,proto3" json:"sfu_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_recording_sfu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetSfuId() string {
	if x != nil {
		return x.SfuId
	}
	return ""
}

func (x *RegisterRequest) GetSfuHost() string {
	if x != nil {
		return x.SfuHost
	}
	return ""
}

func (x *RegisterRequest) GetSfuPort() int32 {
	if x != nil {
		return x.SfuPort
	}
	return 0
}

type RegisterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordingServiceId string                 `protobuf:"bytes,2,opt,name=recording_service_id,json=recordingServiceId,proto3" json:"recording_service_id,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_recording_sfu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetRecordingServiceId() string {
	if x != nil {
		return x.RecordingServiceId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"` // peer_id of who requested recording
	Policy        *RecordingPolicy       `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingRequest) Reset() {
	*x = StartRecordingRequest{}
	mi := &file_recording_sfu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingRequest) ProtoMessage() {}

func (x *StartRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingRequest.ProtoReflect.Descriptor instead.
func (*StartRecordingRequest) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{4}
}

func (x *StartRecordingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartRecordingRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *StartRecordingRequest) GetPolicy() *RecordingPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type StartRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // Unix timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingResponse) Reset() {
	*x = StartRecordingResponse{}
	mi := &file_recording_sfu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingResponse) ProtoMessage() {}

func (x *StartRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingResponse.ProtoReflect.Descriptor instead.
func (*StartRecordingResponse) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{5}
}

func (x *StartRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRecordingResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *StartRecordingResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartRecordingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartRecordingResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type StopRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	StoppedBy     string                 `protobuf:"bytes,3,opt,name=stopped_by,json=stoppedBy,proto3" json:"stopped_by,omitempty"` // peer_id of who stopped recording
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingRequest) Reset() {
	*x = StopRecordingRequest{}
	mi := &file_recording_sfu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingRequest) ProtoMessage() {}

func (x *StopRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingRequest.ProtoReflect.Descriptor instead.
func (*StopRecordingRequest) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{6}
}

func (x *StopRecordingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StopRecordingRequest) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *StopRecordingRequest) GetStoppedBy() string {
	if x != nil {
		return x.StoppedBy
	}
	return ""
}

type StopRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StoppedAt     int64                  `protobuf:"varint,5,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"` // Unix timestamp ms
	Stats         *RecordingStats        `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingResponse) Reset() {
	*x = StopRecordingResponse{}
	mi := &file_recording_sfu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingResponse) ProtoMessage() {}

func (x *StopRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingResponse.ProtoReflect.Descriptor instead.
func (*StopRecordingResponse) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{7}
}

func (x *StopRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRecordingResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *StopRecordingResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StopRecordingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopRecordingResponse) GetStoppedAt() int64 {
	if x != nil {
		return x.StoppedAt
	}
	return 0
}

func (x *StopRecordingResponse) GetStats() *RecordingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SubscribeTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,3,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,5,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	Codec         string                 `protobuf:"bytes,6,opt,name=codec,proto3" json:"codec,omitempty"`
	PayloadType   uint32                 `protobuf:"varint,7,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Ssrc          uint32                 `protobuf:"varint,8,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTrackRequest) Reset() {
	*x = SubscribeTrackRequest{}
	mi := &file_recording_sfu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTrackRequest) ProtoMessage() {}

func (x *SubscribeTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTrackRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTrackRequest) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeTrackRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscribeTrackRequest) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *SubscribeTrackRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *SubscribeTrackRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SubscribeTrackRequest) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

func (x *SubscribeTrackRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SubscribeTrackRequest) GetPayloadType() uint32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *SubscribeTrackRequest) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *SubscribeTrackRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UnsubscribeTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,3,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,5,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeTrackRequest) Reset() {
	*x = UnsubscribeTrackRequest{}
	mi := &file_recording_sfu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeTrackRequest) ProtoMessage() {}

func (x *UnsubscribeTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeTrackRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeTrackRequest) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{9}
}

func (x *UnsubscribeTrackRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnsubscribeTrackRequest) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *UnsubscribeTrackRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *UnsubscribeTrackRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *UnsubscribeTrackRequest) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

func (x *UnsubscribeTrackRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RtpPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RtpData       []byte                 `protobuf:"bytes,4,opt,name=rtp_data,json=rtpData,proto3" json:"rtp_data,omitempty"` // Raw RTP packet bytes
	Ssrc          uint32                 `protobuf:"varint,5,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	PayloadType   uint32                 `protobuf:"varint,6,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Server-side capture timestamp (Unix ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtpPacket) Reset() {
	*x = RtpPacket{}
	mi := &file_recording_sfu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtpPacket) ProtoMessage() {}

func (x *RtpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtpPacket.ProtoReflect.Descriptor instead.
func (*RtpPacket) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{10}
}

func (x *RtpPacket) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtpPacket) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *RtpPacket) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RtpPacket) GetRtpData() []byte {
	if x != nil {
		return x.RtpData
	}
	return nil
}

func (x *RtpPacket) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *RtpPacket) GetPayloadType() uint32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *RtpPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RoomEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RoomId      string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId string                 `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	Timestamp   int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp ms
	// Types that are valid to be assigned to Event:
	//
	//	*RoomEvent_ProducerCreated
	//	*RoomEvent_ProducerClosed
	//	*RoomEvent_ProducerPaused
	//	*RoomEvent_ProducerResumed
	//	*RoomEvent_PeerJoined
	//	*RoomEvent_PeerLeft
	//	*RoomEvent_ActiveSpeaker
	Event         isRoomEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	mi := &file_recording_sfu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{11}
}

func (x *RoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEvent) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *RoomEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RoomEvent) GetEvent() isRoomEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RoomEvent) GetProducerCreated() *ProducerCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_ProducerCreated); ok {
			return x.ProducerCreated
		}
	}
	return nil
}

func (x *RoomEvent) GetProducerClosed() *ProducerClosedEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_ProducerClosed); ok {
			return x.ProducerClosed
		}
	}
	return nil
}

func (x *RoomEvent) GetProducerPaused() *ProducerPausedEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_ProducerPaused); ok {
			return x.ProducerPaused
		}
	}
	return nil
}

func (x *RoomEvent) GetProducerResumed() *ProducerResumedEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_ProducerResumed); ok {
			return x.ProducerResumed
		}
	}
	return nil
}

func (x *RoomEvent) GetPeerJoined() *PeerJoinedEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_PeerJoined); ok {
			return x.PeerJoined
		}
	}
	return nil
}

func (x *RoomEvent) GetPeerLeft() *PeerLeftEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_PeerLeft); ok {
			return x.PeerLeft
		}
	}
	return nil
}

func (x *RoomEvent) GetActiveSpeaker() *ActiveSpeakerEvent {
	if x != nil {
		if x, ok := x.Event.(*RoomEvent_ActiveSpeaker); ok {
			return x.ActiveSpeaker
		}
	}
	return nil
}

type isRoomEvent_Event interface {
	isRoomEvent_Event()
}

type RoomEvent_ProducerCreated struct {
	ProducerCreated *ProducerCreatedEvent `protobuf:"bytes,4,opt,name=producer_created,json=producerCreated,proto3,oneof"`
}

type RoomEvent_ProducerClosed struct {
	ProducerClosed *ProducerClosedEvent `protobuf:"bytes,5,opt,name=producer_closed,json=producerClosed,proto3,oneof"`
}

type RoomEvent_ProducerPaused struct {
	ProducerPaused *ProducerPausedEvent `protobuf:"bytes,6,opt,name=producer_paused,json=producerPaused,proto3,oneof"`
}

type RoomEvent_ProducerResumed struct {
	ProducerResumed *ProducerResumedEvent `protobuf:"bytes,7,opt,name=producer_resumed,json=producerResumed,proto3,oneof"`
}

type RoomEvent_PeerJoined struct {
	PeerJoined *PeerJoinedEvent `protobuf:"bytes,8,opt,name=peer_joined,json=peerJoined,proto3,oneof"`
}

type RoomEvent_PeerLeft struct {
	PeerLeft *PeerLeftEvent `protobuf:"bytes,9,opt,name=peer_left,json=peerLeft,proto3,oneof"`
}

type RoomEvent_ActiveSpeaker struct {
	ActiveSpeaker *ActiveSpeakerEvent `protobuf:"bytes,10,opt,name=active_speaker,json=activeSpeaker,proto3,oneof"`
}

func (*RoomEvent_ProducerCreated) isRoomEvent_Event() {}

func (*RoomEvent_ProducerClosed) isRoomEvent_Event() {}

func (*RoomEvent_ProducerPaused) isRoomEvent_Event() {}

func (*RoomEvent_ProducerResumed) isRoomEvent_Event() {}

func (*RoomEvent_PeerJoined) isRoomEvent_Event() {}

func (*RoomEvent_PeerLeft) isRoomEvent_Event() {}

func (*RoomEvent_ActiveSpeaker) isRoomEvent_Event() {}

type ProducerCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,3,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	PayloadType   uint32                 `protobuf:"varint,5,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Ssrc          uint32                 `protobuf:"varint,6,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerCreatedEvent) Reset() {
	*x = ProducerCreatedEvent{}
	mi := &file_recording_sfu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerCreatedEvent) ProtoMessage() {}

func (x *ProducerCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerCreatedEvent.ProtoReflect.Descriptor instead.
func (*ProducerCreatedEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{12}
}

func (x *ProducerCreatedEvent) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ProducerCreatedEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ProducerCreatedEvent) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

func (x *ProducerCreatedEvent) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ProducerCreatedEvent) GetPayloadType() uint32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *ProducerCreatedEvent) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

type ProducerClosedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,3,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerClosedEvent) Reset() {
	*x = ProducerClosedEvent{}
	mi := &file_recording_sfu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerClosedEvent) ProtoMessage() {}

func (x *ProducerClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerClosedEvent.ProtoReflect.Descriptor instead.
func (*ProducerClosedEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{13}
}

func (x *ProducerClosedEvent) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ProducerClosedEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ProducerClosedEvent) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

type ProducerPausedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,3,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerPausedEvent) Reset() {
	*x = ProducerPausedEvent{}
	mi := &file_recording_sfu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerPausedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerPausedEvent) ProtoMessage() {}

func (x *ProducerPausedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerPausedEvent.ProtoReflect.Descriptor instead.
func (*ProducerPausedEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{14}
}

func (x *ProducerPausedEvent) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ProducerPausedEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ProducerPausedEvent) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

type ProducerResumedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TrackType     TrackType              `protobuf:"varint,3,opt,name=track_type,json=trackType,proto3,enum=recording.TrackType" json:"track_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerResumedEvent) Reset() {
	*x = ProducerResumedEvent{}
	mi := &file_recording_sfu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerResumedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerResumedEvent) ProtoMessage() {}

func (x *ProducerResumedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerResumedEvent.ProtoReflect.Descriptor instead.
func (*ProducerResumedEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{15}
}

func (x *ProducerResumedEvent) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ProducerResumedEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ProducerResumedEvent) GetTrackType() TrackType {
	if x != nil {
		return x.TrackType
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

type PeerJoinedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerJoinedEvent) Reset() {
	*x = PeerJoinedEvent{}
	mi := &file_recording_sfu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerJoinedEvent) ProtoMessage() {}

func (x *PeerJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerJoinedEvent.ProtoReflect.Descriptor instead.
func (*PeerJoinedEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{16}
}

func (x *PeerJoinedEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerJoinedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type PeerLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerLeftEvent) Reset() {
	*x = PeerLeftEvent{}
	mi := &file_recording_sfu_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerLeftEvent) ProtoMessage() {}

func (x *PeerLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerLeftEvent.ProtoReflect.Descriptor instead.
func (*PeerLeftEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{17}
}

func (x *PeerLeftEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type ActiveSpeakerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSpeakerEvent) Reset() {
	*x = ActiveSpeakerEvent{}
	mi := &file_recording_sfu_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSpeakerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSpeakerEvent) ProtoMessage() {}

func (x *ActiveSpeakerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSpeakerEvent.ProtoReflect.Descriptor instead.
func (*ActiveSpeakerEvent) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{18}
}

func (x *ActiveSpeakerEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type RecordingPolicy struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Enabled                      bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WhoCanRecord                 WhoCanRecord           `protobuf:"varint,2,opt,name=who_can_record,json=whoCanRecord,proto3,enum=recording.WhoCanRecord" json:"who_can_record,omitempty"` // Placeholder for future participant recording
	AutoRecord                   bool                   `protobuf:"varint,3,opt,name=auto_record,json=autoRecord,proto3" json:"auto_record,omitempty"`
	RecordAudio                  bool                   `protobuf:"varint,4,opt,name=record_audio,json=recordAudio,proto3" json:"record_audio,omitempty"`
	RecordVideo                  bool                   `protobuf:"varint,5,opt,name=record_video,json=recordVideo,proto3" json:"record_video,omitempty"`
	RecordScreenshare            bool                   `protobuf:"varint,6,opt,name=record_screenshare,json=recordScreenshare,proto3" json:"record_screenshare,omitempty"`
	WhoCanAccessRecordings       AccessLevel            `protobuf:"varint,7,opt,name=who_can_access_recordings,json=whoCanAccessRecordings,proto3,enum=recording.AccessLevel" json:"who_can_access_recordings,omitempty"` // Post-meeting access control
	AllowedAccessorIds           []string               `protobuf:"bytes,8,rep,name=allowed_accessor_ids,json=allowedAccessorIds,proto3" json:"allowed_accessor_ids,omitempty"`                                           // User IDs when ACCESS_SELECTED
	AutoRecordQuickAccess        bool                   `protobuf:"varint,9,opt,name=auto_record_quick_access,json=autoRecordQuickAccess,proto3" json:"auto_record_quick_access,omitempty"`
	AutoRecordLateComposite      bool                   `protobuf:"varint,10,opt,name=auto_record_late_composite,json=autoRecordLateComposite,proto3" json:"auto_record_late_composite,omitempty"`
	QuickAccessPartDurationSec   int32                  `protobuf:"varint,11,opt,name=quick_access_part_duration_sec,json=quickAccessPartDurationSec,proto3" json:"quick_access_part_duration_sec,omitempty"`
	LateCompositePartDurationSec int32                  `protobuf:"varint,12,opt,name=late_composite_part_duration_sec,json=lateCompositePartDurationSec,proto3" json:"late_composite_part_duration_sec,omitempty"`
	QuickAccessLayout            RecordingLayout        `protobuf:"varint,13,opt,name=quick_access_layout,json=quickAccessLayout,proto3,enum=recording.RecordingLayout" json:"quick_access_layout,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RecordingPolicy) Reset() {
	*x = RecordingPolicy{}
	mi := &file_recording_sfu_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingPolicy) ProtoMessage() {}

func (x *RecordingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingPolicy.ProtoReflect.Descriptor instead.
func (*RecordingPolicy) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{19}
}

func (x *RecordingPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RecordingPolicy) GetWhoCanRecord() WhoCanRecord {
	if x != nil {
		return x.WhoCanRecord
	}
	return WhoCanRecord_WHO_CAN_RECORD_UNSPECIFIED
}

func (x *RecordingPolicy) GetAutoRecord() bool {
	if x != nil {
		return x.AutoRecord
	}
	return false
}

func (x *RecordingPolicy) GetRecordAudio() bool {
	if x != nil {
		return x.RecordAudio
	}
	return false
}

func (x *RecordingPolicy) GetRecordVideo() bool {
	if x != nil {
		return x.RecordVideo
	}
	return false
}

func (x *RecordingPolicy) GetRecordScreenshare() bool {
	if x != nil {
		return x.RecordScreenshare
	}
	return false
}

func (x *RecordingPolicy) GetWhoCanAccessRecordings() AccessLevel {
	if x != nil {
		return x.WhoCanAccessRecordings
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *RecordingPolicy) GetAllowedAccessorIds() []string {
	if x != nil {
		return x.AllowedAccessorIds
	}
	return nil
}

func (x *RecordingPolicy) GetAutoRecordQuickAccess() bool {
	if x != nil {
		return x.AutoRecordQuickAccess
	}
	return false
}

func (x *RecordingPolicy) GetAutoRecordLateComposite() bool {
	if x != nil {
		return x.AutoRecordLateComposite
	}
	return false
}

func (x *RecordingPolicy) GetQuickAccessPartDurationSec() int32 {
	if x != nil {
		return x.QuickAccessPartDurationSec
	}
	return 0
}

func (x *RecordingPolicy) GetLateCompositePartDurationSec() int32 {
	if x != nil {
		return x.LateCompositePartDurationSec
	}
	return 0
}

func (x *RecordingPolicy) GetQuickAccessLayout() RecordingLayout {
	if x != nil {
		return x.QuickAccessLayout
	}
	return RecordingLayout_RECORDING_LAYOUT_UNSPECIFIED
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_recording_sfu_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{20}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RecordingId   string                 `protobuf:"bytes,4,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_recording_sfu_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{21}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ErrorMessage) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

type RecordingStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	TrackCount    int32                  `protobuf:"varint,3,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	PeerCount     int32                  `protobuf:"varint,4,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingStats) Reset() {
	*x = RecordingStats{}
	mi := &file_recording_sfu_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingStats) ProtoMessage() {}

func (x *RecordingStats) ProtoReflect() protoreflect.Message {
	mi := &file_recording_sfu_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingStats.ProtoReflect.Descriptor instead.
func (*RecordingStats) Descriptor() ([]byte, []int) {
	return file_recording_sfu_proto_rawDescGZIP(), []int{22}
}

func (x *RecordingStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordingStats) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *RecordingStats) GetTrackCount() int32 {
	if x != nil {
		return x.TrackCount
	}
	return 0
}

func (x *RecordingStats) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

var File_recording_sfu_proto protoreflect.FileDescriptor

const file_recording_sfu_proto_rawDesc = "" +
	"\n" +
	"\x13recording_sfu.proto\x12\trecording\"\x89\x03\n" +
	"\x0eRecordingToSfu\x12J\n" +
	"\x11register_response\x18\x01 \x01(\v2\x1b.recording.RegisterResponseH\x00R\x10registerResponse\x12]\n" +
	"\x18start_recording_response\x18\x02 \x01(\v2!.recording.StartRecordingResponseH\x00R\x16startRecordingResponse\x12Z\n" +
	"\x17stop_recording_response\x18\x03 \x01(\v2 .recording.StopRecordingResponseH\x00R\x15stopRecordingResponse\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x17.recording.ErrorMessageH\x00R\x05error\x124\n" +
	"\theartbeat\x18\x05 \x01(\v2\x14.recording.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"\xb0\x04\n" +
	"\x0eSfuToRecording\x128\n" +
	"\bregister\x18\x01 \x01(\v2\x1a.recording.RegisterRequestH\x00R\bregister\x12K\n" +
	"\x0fstart_recording\x18\x02 \x01(\v2 .recording.StartRecordingRequestH\x00R\x0estartRecording\x12H\n" +
	"\x0estop_recording\x18\x03 \x01(\v2\x1f.recording.StopRecordingRequestH\x00R\rstopRecording\x12K\n" +
	"\x0fsubscribe_track\x18\x04 \x01(\v2 .recording.SubscribeTrackRequestH\x00R\x0esubscribeTrack\x12Q\n" +
	"\x11unsubscribe_track\x18\x05 \x01(\v2\".recording.UnsubscribeTrackRequestH\x00R\x10unsubscribeTrack\x125\n" +
	"\n" +
	"rtp_packet\x18\x06 \x01(\v2\x14.recording.RtpPacketH\x00R\trtpPacket\x125\n" +
	"\n" +
	"room_event\x18\a \x01(\v2\x14.recording.RoomEventH\x00R\troomEvent\x124\n" +
	"\theartbeat\x18\b \x01(\v2\x14.recording.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"^\n" +
	"\x0fRegisterRequest\x12\x15\n" +
	"\x06sfu_id\x18\x01 \x01(\tR\x05sfuId\x12\x19\n" +
	"\bsfu_host\x18\x02 \x01(\tR\asfuHost\x12\x19\n" +
	"\bsfu_port\x18\x03 \x01(\x05R\asfuPort\"x\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x14recording_service_id\x18\x02 \x01(\tR\x12recordingServiceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x87\x01\n" +
	"\x15StartRecordingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frequested_by\x18\x02 \x01(\tR\vrequestedBy\x122\n" +
	"\x06policy\x18\x03 \x01(\v2\x1a.recording.RecordingPolicyR\x06policy\"\xa7\x01\n" +
	"\x16StartRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\"q\n" +
	"\x14StopRecordingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x1d\n" +
	"\n" +
	"stopped_by\x18\x03 \x01(\tR\tstoppedBy\"\xd7\x01\n" +
	"\x15StopRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x05 \x01(\x03R\tstoppedAt\x12/\n" +
	"\x05stats\x18\x06 \x01(\v2\x19.recording.RecordingStatsR\x05stats\"\xad\x02\n" +
	"\x15SubscribeTrackRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x1f\n" +
	"\vproducer_id\x18\x03 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x05 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\x12\x14\n" +
	"\x05codec\x18\x06 \x01(\tR\x05codec\x12!\n" +
	"\fpayload_type\x18\a \x01(\rR\vpayloadType\x12\x12\n" +
	"\x04ssrc\x18\b \x01(\rR\x04ssrc\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\xe2\x01\n" +
	"\x17UnsubscribeTrackRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x1f\n" +
	"\vproducer_id\x18\x03 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x05 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xce\x01\n" +
	"\tRtpPacket\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x12\x19\n" +
	"\brtp_data\x18\x04 \x01(\fR\artpData\x12\x12\n" +
	"\x04ssrc\x18\x05 \x01(\rR\x04ssrc\x12!\n" +
	"\fpayload_type\x18\x06 \x01(\rR\vpayloadType\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xe0\x04\n" +
	"\tRoomEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x02 \x01(\tR\vrecordingId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12L\n" +
	"\x10producer_created\x18\x04 \x01(\v2\x1f.recording.ProducerCreatedEventH\x00R\x0fproducerCreated\x12I\n" +
	"\x0fproducer_closed\x18\x05 \x01(\v2\x1e.recording.ProducerClosedEventH\x00R\x0eproducerClosed\x12I\n" +
	"\x0fproducer_paused\x18\x06 \x01(\v2\x1e.recording.ProducerPausedEventH\x00R\x0eproducerPaused\x12L\n" +
	"\x10producer_resumed\x18\a \x01(\v2\x1f.recording.ProducerResumedEventH\x00R\x0fproducerResumed\x12=\n" +
	"\vpeer_joined\x18\b \x01(\v2\x1a.recording.PeerJoinedEventH\x00R\n" +
	"peerJoined\x127\n" +
	"\tpeer_left\x18\t \x01(\v2\x18.recording.PeerLeftEventH\x00R\bpeerLeft\x12F\n" +
	"\x0eactive_speaker\x18\n" +
	" \x01(\v2\x1d.recording.ActiveSpeakerEventH\x00R\ractiveSpeakerB\a\n" +
	"\x05event\"\xd2\x01\n" +
	"\x14ProducerCreatedEvent\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x03 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12!\n" +
	"\fpayload_type\x18\x05 \x01(\rR\vpayloadType\x12\x12\n" +
	"\x04ssrc\x18\x06 \x01(\rR\x04ssrc\"\x84\x01\n" +
	"\x13ProducerClosedEvent\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x03 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\"\x84\x01\n" +
	"\x13ProducerPausedEvent\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x03 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\"\x85\x01\n" +
	"\x14ProducerResumedEvent\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x123\n" +
	"\n" +
	"track_type\x18\x03 \x01(\x0e2\x14.recording.TrackTypeR\ttrackType\"M\n" +
	"\x0fPeerJoinedEvent\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"(\n" +
	"\rPeerLeftEvent\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"-\n" +
	"\x12ActiveSpeakerEvent\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\xd3\x05\n" +
	"\x0fRecordingPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12=\n" +
	"\x0ewho_can_record\x18\x02 \x01(\x0e2\x17.recording.WhoCanRecordR\fwhoCanRecord\x12\x1f\n" +
	"\vauto_record\x18\x03 \x01(\bR\n" +
	"autoRecord\x12!\n" +
	"\frecord_audio\x18\x04 \x01(\bR\vrecordAudio\x12!\n" +
	"\frecord_video\x18\x05 \x01(\bR\vrecordVideo\x12-\n" +
	"\x12record_screenshare\x18\x06 \x01(\bR\x11recordScreenshare\x12Q\n" +
	"\x19who_can_access_recordings\x18\a \x01(\x0e2\x16.recording.AccessLevelR\x16whoCanAccessRecordings\x120\n" +
	"\x14allowed_accessor_ids\x18\b \x03(\tR\x12allowedAccessorIds\x127\n" +
	"\x18auto_record_quick_access\x18\t \x01(\bR\x15autoRecordQuickAccess\x12;\n" +
	"\x1aauto_record_late_composite\x18\n" +
	" \x01(\bR\x17autoRecordLateComposite\x12B\n" +
	"\x1equick_access_part_duration_sec\x18\v \x01(\x05R\x1aquickAccessPartDurationSec\x12F\n" +
	" late_composite_part_duration_sec\x18\f \x01(\x05R\x1clateCompositePartDurationSec\x12J\n" +
	"\x13quick_access_layout\x18\r \x01(\x0e2\x1a.recording.RecordingLayoutR\x11quickAccessLayout\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"x\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12!\n" +
	"\frecording_id\x18\x04 \x01(\tR\vrecordingId\"\x92\x01\n" +
	"\x0eRecordingStats\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1f\n" +
	"\vtrack_count\x18\x03 \x01(\x05R\n" +
	"trackCount\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x04 \x01(\x05R\tpeerCount*_\n" +
	"\fWhoCanRecord\x12\x1e\n" +
	"\x1aWHO_CAN_RECORD_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHOST_ONLY\x10\x01\x12\x14\n" +
	"\x10CO_HOST_AND_HOST\x10\x02\x12\n" +
	"\n" +
	"\x06ANYONE\x10\x03*w\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ACCESS_ALL\x10\x01\x12\x0f\n" +
	"\vACCESS_HOST\x10\x02\x12\x14\n" +
	"\x10ACCESS_LOGGED_IN\x10\x03\x12\x13\n" +
	"\x0fACCESS_SELECTED\x10\x04*N\n" +
	"\tTrackType\x12\x1a\n" +
	"\x16TRACK_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05AUDIO\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\x0f\n" +
	"\vSCREENSHARE\x10\x03*N\n" +
	"\x0fRecordingLayout\x12 \n" +
	"\x1cRECORDING_LAYOUT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RECORDING_LAYOUT_GRID\x10\x012Y\n" +
	"\x12RecordingSfuBridge\x12C\n" +
	"\aConnect\x12\x19.recording.SfuToRecording\x1a\x19.recording.RecordingToSfu(\x010\x01B&Z$github.com/brollyhub/recording/protob\x06proto3"

var (
	file_recording_sfu_proto_rawDescOnce sync.Once
	file_recording_sfu_proto_rawDescData []byte
)

func file_recording_sfu_proto_rawDescGZIP() []byte {
	file_recording_sfu_proto_rawDescOnce.Do(func() {
		file_recording_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recording_sfu_proto_rawDesc), len(file_recording_sfu_proto_rawDesc)))
	})
	return file_recording_sfu_proto_rawDescData
}

var file_recording_sfu_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_recording_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_recording_sfu_proto_goTypes = []any{
	(WhoCanRecord)(0),               // 0: recording.WhoCanRecord
	(AccessLevel)(0),                // 1: recording.AccessLevel
	(TrackType)(0),                  // 2: recording.TrackType
	(RecordingLayout)(0),            // 3: recording.RecordingLayout
	(*RecordingToSfu)(nil),          // 4: recording.RecordingToSfu
	(*SfuToRecording)(nil),          // 5: recording.SfuToRecording
	(*RegisterRequest)(nil),         // 6: recording.RegisterRequest
	(*RegisterResponse)(nil),        // 7: recording.RegisterResponse
	(*StartRecordingRequest)(nil),   // 8: recording.StartRecordingRequest
	(*StartRecordingResponse)(nil),  // 9: recording.StartRecordingResponse
	(*StopRecordingRequest)(nil),    // 10: recording.StopRecordingRequest
	(*StopRecordingResponse)(nil),   // 11: recording.StopRecordingResponse
	(*SubscribeTrackRequest)(nil),   // 12: recording.SubscribeTrackRequest
	(*UnsubscribeTrackRequest)(nil), // 13: recording.UnsubscribeTrackRequest
	(*RtpPacket)(nil),               // 14: recording.RtpPacket
	(*RoomEvent)(nil),               // 15: recording.RoomEvent
	(*ProducerCreatedEvent)(nil),    // 16: recording.ProducerCreatedEvent
	(*ProducerClosedEvent)(nil),     // 17: recording.ProducerClosedEvent
	(*ProducerPausedEvent)(nil),     // 18: recording.ProducerPausedEvent
	(*ProducerResumedEvent)(nil),    // 19: recording.ProducerResumedEvent
	(*PeerJoinedEvent)(nil),         // 20: recording.PeerJoinedEvent
	(*PeerLeftEvent)(nil),           // 21: recording.PeerLeftEvent
	(*ActiveSpeakerEvent)(nil),      // 22: recording.ActiveSpeakerEvent
	(*RecordingPolicy)(nil),         // 23: recording.RecordingPolicy
	(*Heartbeat)(nil),               // 24: recording.Heartbeat
	(*ErrorMessage)(nil),            // 25: recording.ErrorMessage
	(*RecordingStats)(nil),          // 26: recording.RecordingStats
}
var file_recording_sfu_proto_depIdxs = []int32{
	7,  // 0: recording.RecordingToSfu.register_response:type_name -> recording.RegisterResponse
	9,  // 1: recording.RecordingToSfu.start_recording_response:type_name -> recording.StartRecordingResponse
	11, // 2: recording.RecordingToSfu.stop_recording_response:type_name -> recording.StopRecordingResponse
	25, // 3: recording.RecordingToSfu.error:type_name -> recording.ErrorMessage
	24, // 4: recording.RecordingToSfu.heartbeat:type_name -> recording.Heartbeat
	6,  // 5: recording.SfuToRecording.register:type_name -> recording.RegisterRequest
	8,  // 6: recording.SfuToRecording.start_recording:type_name -> recording.StartRecordingRequest
	10, // 7: recording.SfuToRecording.stop_recording:type_name -> recording.StopRecordingRequest
	12, // 8: recording.SfuToRecording.subscribe_track:type_name -> recording.SubscribeTrackRequest
	13, // 9: recording.SfuToRecording.unsubscribe_track:type_name -> recording.UnsubscribeTrackRequest
	14, // 10: recording.SfuToRecording.rtp_packet:type_name -> recording.RtpPacket
	15, // 11: recording.SfuToRecording.room_event:type_name -> recording.RoomEvent
	24, // 12: recording.SfuToRecording.heartbeat:type_name -> recording.Heartbeat
	23, // 13: recording.StartRecordingRequest.policy:type_name -> recording.RecordingPolicy
	26, // 14: recording.StopRecordingResponse.stats:type_name -> recording.RecordingStats
	2,  // 15: recording.SubscribeTrackRequest.track_type:type_name -> recording.TrackType
	2,  // 16: recording.UnsubscribeTrackRequest.track_type:type_name -> recording.TrackType
	16, // 17: recording.RoomEvent.producer_created:type_name -> recording.ProducerCreatedEvent
	17, // 18: recording.RoomEvent.producer_closed:type_name -> recording.ProducerClosedEvent
	18, // 19: recording.RoomEvent.producer_paused:type_name -> recording.ProducerPausedEvent
	19, // 20: recording.RoomEvent.producer_resumed:type_name -> recording.ProducerResumedEvent
	20, // 21: recording.RoomEvent.peer_joined:type_name -> recording.PeerJoinedEvent
	21, // 22: recording.RoomEvent.peer_left:type_name -> recording.PeerLeftEvent
	22, // 23: recording.RoomEvent.active_speaker:type_name -> recording.ActiveSpeakerEvent
	2,  // 24: recording.ProducerCreatedEvent.track_type:type_name -> recording.TrackType
	2,  // 25: recording.ProducerClosedEvent.track_type:type_name -> recording.TrackType
	2,  // 26: recording.ProducerPausedEvent.track_type:type_name -> recording.TrackType
	2,  // 27: recording.ProducerResumedEvent.track_type:type_name -> recording.TrackType
	0,  // 28: recording.RecordingPolicy.who_can_record:type_name -> recording.WhoCanRecord
	1,  // 29: recording.RecordingPolicy.who_can_access_recordings:type_name -> recording.AccessLevel
	3,  // 30: recording.RecordingPolicy.quick_access_layout:type_name -> recording.RecordingLayout
	5,  // 31: recording.RecordingSfuBridge.Connect:input_type -> recording.SfuToRecording
	4,  // 32: recording.RecordingSfuBridge.Connect:output_type -> recording.RecordingToSfu
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_recording_sfu_proto_init() }
func file_recording_sfu_proto_init() {
	if File_recording_sfu_proto != nil {
		return
	}
	file_recording_sfu_proto_msgTypes[0].OneofWrappers = []any{
		(*RecordingToSfu_RegisterResponse)(nil),
		(*RecordingToSfu_StartRecordingResponse)(nil),
		(*RecordingToSfu_StopRecordingResponse)(nil),
		(*RecordingToSfu_Error)(nil),
		(*RecordingToSfu_Heartbeat)(nil),
	}
	file_recording_sfu_proto_msgTypes[1].OneofWrappers = []any{
		(*SfuToRecording_Register)(nil),
		(*SfuToRecording_StartRecording)(nil),
		(*SfuToRecording_StopRecording)(nil),
		(*SfuToRecording_SubscribeTrack)(nil),
		(*SfuToRecording_UnsubscribeTrack)(nil),
		(*SfuToRecording_RtpPacket)(nil),
		(*SfuToRecording_RoomEvent)(nil),
		(*SfuToRecording_Heartbeat)(nil),
	}
	file_recording_sfu_proto_msgTypes[11].OneofWrappers = []any{
		(*RoomEvent_ProducerCreated)(nil),
		(*RoomEvent_ProducerClosed)(nil),
		(*RoomEvent_ProducerPaused)(nil),
		(*RoomEvent_ProducerResumed)(nil),
		(*RoomEvent_PeerJoined)(nil),
		(*RoomEvent_PeerLeft)(nil),
		(*RoomEvent_ActiveSpeaker)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recording_sfu_proto_rawDesc), len(file_recording_sfu_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recording_sfu_proto_goTypes,
		DependencyIndexes: file_recording_sfu_proto_depIdxs,
		EnumInfos:         file_recording_sfu_proto_enumTypes,
		MessageInfos:      file_recording_sfu_proto_msgTypes,
	}.Build()
	File_recording_sfu_proto = out.File
	file_recording_sfu_proto_goTypes = nil
	file_recording_sfu_proto_depIdxs = nil
}
