// recording_sfu.proto
// Protocol definitions for SFU ↔ Recording Service communication
// This defines the bidirectional gRPC stream for recording RTP packets
// and room events for server-side recording.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: recording_sfu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordingSfuBridge_Connect_FullMethodName = "/recording.RecordingSfuBridge/Connect"
)

// RecordingSfuBridgeClient is the client API for RecordingSfuBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordingSfuBridgeClient interface {
	// Connect establishes a bidirectional stream for recording operations
	// SFU connects and sends RTP packets + events, Recording Service responds
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SfuToRecording, RecordingToSfu], error)
}

type recordingSfuBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingSfuBridgeClient(cc grpc.ClientConnInterface) RecordingSfuBridgeClient {
	return &recordingSfuBridgeClient{cc}
}

func (c *recordingSfuBridgeClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SfuToRecording, RecordingToSfu], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecordingSfuBridge_ServiceDesc.Streams[0], RecordingSfuBridge_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SfuToRecording, RecordingToSfu]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordingSfuBridge_ConnectClient = grpc.BidiStreamingClient[SfuToRecording, RecordingToSfu]

// RecordingSfuBridgeServer is the server API for RecordingSfuBridge service.
// All implementations must embed UnimplementedRecordingSfuBridgeServer
// for forward compatibility.
type RecordingSfuBridgeServer interface {
	// Connect establishes a bidirectional stream for recording operations
	// SFU connects and sends RTP packets + events, Recording Service responds
	Connect(grpc.BidiStreamingServer[SfuToRecording, RecordingToSfu]) error
	mustEmbedUnimplementedRecordingSfuBridgeServer()
}

// UnimplementedRecordingSfuBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordingSfuBridgeServer struct{}

func (UnimplementedRecordingSfuBridgeServer) Connect(grpc.BidiStreamingServer[SfuToRecording, RecordingToSfu]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRecordingSfuBridgeServer) mustEmbedUnimplementedRecordingSfuBridgeServer() {}
func (UnimplementedRecordingSfuBridgeServer) testEmbeddedByValue()                            {}

// UnsafeRecordingSfuBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingSfuBridgeServer will
// result in compilation errors.
type UnsafeRecordingSfuBridgeServer interface {
	mustEmbedUnimplementedRecordingSfuBridgeServer()
}

func RegisterRecordingSfuBridgeServer(s grpc.ServiceRegistrar, srv RecordingSfuBridgeServer) {
	// If the following call panics, it indicates UnimplementedRecordingSfuBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordingSfuBridge_ServiceDesc, srv)
}

func _RecordingSfuBridge_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecordingSfuBridgeServer).Connect(&grpc.GenericServerStream[SfuToRecording, RecordingToSfu]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordingSfuBridge_ConnectServer = grpc.BidiStreamingServer[SfuToRecording, RecordingToSfu]

// RecordingSfuBridge_ServiceDesc is the grpc.ServiceDesc for RecordingSfuBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingSfuBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recording.RecordingSfuBridge",
	HandlerType: (*RecordingSfuBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RecordingSfuBridge_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "recording_sfu.proto",
}
